//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compute_node
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string database { get; set; }
        public string instance { get; set; }
        public bool active { get; set; }
        public int index { get; set; }
        public string driveletter { get; set; }
    }
}
