//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration_properties
    {
        public string id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public string @default { get; set; }
        public short protection { get; set; }
        public short access { get; set; }
        public string datatype { get; set; }
    }
}
