//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class database_file
    {
        public int filegroup_id { get; set; }
        public int sequence { get; set; }
        public string root_path { get; set; }
        public bool is_add_from_alter { get; set; }
        public Nullable<double> percent_allocated_space { get; set; }
    }
}
