//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filegroup
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> distribution_id { get; set; }
        public string min_filesize { get; set; }
        public string max_filesize { get; set; }
        public string default_filegrowth { get; set; }
        public int type { get; set; }
        public bool is_shell { get; set; }
    }
}
