//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdw_sp_configure
    {
        public string name { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<int> maximum { get; set; }
        public Nullable<int> config_value { get; set; }
        public Nullable<int> run_value { get; set; }
    }
}
