//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class standardList
    {
        public int StandardID { get; set; }
        public string StandardName { get; set; }
    }
}
